### ISSUE TITLE
AgentWorkbench not starting after update

### ISSUE THREAD

**Issue by NLoos** [EnFlexIT/AgentWorkbench#1]
Sometimes after installing Agent.Workbench updates, the application fails to start. The log file says the bundle org.agentgui.core cannot be resolved due to constraint violations, "because it is exposed ... via two dependency chains" - [full log file attached](https://github.com/EnFlexIT/AgentWorkbench/files/3516132/1566201966090.log). The problem only occurs when updating from an older version though, when using a clean new install the new version works without any problems.

**Comment by CDerksen** [comment]
We know about this issue, but we don't know the exact reason for that yet.

The p2 update process downloads and installs the updates, but the application does not restart properly. Instead we get a prompt, saying that an error log can be found in the configuration directory (e.g. ./configuration/1566219150305.log). 

Looking for a solution in the Eclipse community, we found [this post](https://www.eclipse.org/forums/index.php/t/823236/) that reports similar problems with an Eclipse update. Following the proposed solution, however, also solves the described problem:

Go to the directory ./configuration/org.eclipse.osgi/.manager. There you’ll find files such as ‘.fileTable.X’ and ‘.fileTableLock’. Delete these files and restart Agent.Workbench. For most users this solves the problem and AWB came up in the latest version.

If this does not solve the issue, we currently can only recommend to download the [latest AWB-Release](https://github.com/EnFlexIT/AgentWorkbench/releases)  and make a clean install.

Hope this helps!
