### ISSUE TITLE
undefined path in javadoc search

### ISSUE THREAD

**Issue by TBrandhorst** [EnFlexIT/AgentWorkbench#14]

**Comment by CDerksen** [comment]
I finally could solve the problem when generating the JavaDoc and getting broken links with the search ([e.g. as described here](https://stackoverflow.com/questions/53732632/gradle-javadoc-search-redirects-to-undefined-url)):

Adding the _--no-module-directories_ flag in the additional javadoc arguments in the pom of project org.agentgui.help resolved the problem.

See: a5bccc2054cca2199772d29aaa44d5fc2441d218
