### ISSUE TITLE
Class.newInstance()

### ISSUE THREAD

**Issue by CDerksen** [EnFlexIT/AgentWorkbench#3]
=> deprecated since J9
Substitute its corresponding usage

**Comment by TBrandhorst** [comment]
In den Klassen NetworkModel NetworkComponentFactory müssen die Fehlermeldungen in den Catch Blöcken spezifiziert werden. Ist als java TODO gekennzeichnet. Ich war mir nicht sicher, was ich da eintragen sollte.

**Comment by TBrandhorst** [comment]
Warum ich newInstance() mit getDeclaredConstructor().newInstance() ersetzt habe:
https://stackoverflow.com/questions/56079042/fix-to-java-newinstance-deprecated/56084044
https://stackoverflow.com/questions/53257073/java-9-replace-class-newinstance

**Comment by tobirobi** [comment]
@TBrandhorst Try to find valid error messages based on the catched error, e.g. for SecurityException: "Loading of AbstractGraphElementPrototype class led to a security violation" (or. similar)
