### ISSUE TITLE
Check for running Java JRE's that can be recommended by us!

### ISSUE THREAD

**Issue by CDerksen** [EnFlexIT/AgentWorkbench#8]
E.g. provide an own JRE for AWB with justj (see https://www.eclipse.org/justj/) or use a ready made JRE's and its installer (see https://adoptopenjdk.net/)

**Comment by TBrandhorst** [comment]
> 
> 
> E.g. provide an own JRE for AWB with justj (see https://www.eclipse.org/justj/) or use a ready made JRE's and its installer (see https://adoptopenjdk.net/)

One **major change** of Java 9 is that Java is now a **modular platform**. Thus, you need to create/specify your own jre with the modules you need. You can use tools like JLink to do so. If found an [online tool](https://justinmahar.github.io/easyjre/) ,which maybe  can help us . Furthermore there are Introductions how to define your own JRE with [JLink ](https://www.baeldung.com/jlink). 

In this [blog](https://stackoverflow.com/questions/58250782/which-free-version-of-java-can-i-use-for-production-environments-and-or-commerci) from stackoverflow, you can see which JDKs can be used for free. Below you find a list of some of them.

**Comment by TBrandhorst** [comment]
## Amazon Cornetto
- no-cost, multiplatform, production-ready distribution of the OpenJDK
- Multiplatform-support (available for Windows, Linux and Mac)
- Compatible with JAVA SE-Platform
- Long Term Suppor (LTS) until 2024 
- No standard JRE for java 11 (only for Linux)
- **Goal:** support Amazon Linux and optimizations for Amazon services

**Comment by TBrandhorst** [comment]
## Azul Zulu
- Multiplatform-support
- Download: https://www.azul.com/downloads/?version=java-11-lts&os=windows&package=jre
- JRE Download for Java 11 possible 
- Lower price than an Oracle Java SE subscription
- No proprietary licenses or “field of use” restrictions
- Verified TCK compliant with Java SE

**Comment by TBrandhorst** [comment]
## Adopt Open JDK ( Eclipse Adoptium)
- Multiplatform-support
- Not tested with Java Technlogy Compatibility Kit
- Top Level Project of Eclipse Foundation since March 2021
- Direct download of JRE possible via this [link](https://adoptopenjdk.net/installation.html#x86-32_win-jre), for JDK [11](https://adoptium.net/releases.html?variant=openjdk11)
- LTS for 4 years

**Comment by TBrandhorst** [comment]
## Eclipse Open J9
- originally built to run on mobile devices with limited memory and it’s been optimized for fast startup, lower memory footprint, and quick ramp-up
- compliant for Java SE
- Supporting JDK levels as long as they are supported by the OpenJDK project
- Number of different garbage collection policies

**Comment by TBrandhorst** [comment]
## Microsoft’s OpenJdk Build 
- providing Windows-specific optimizations
- Multiplatform-support
- open-source, no-cost long-term support (LTS) distribution of OpenJDK that is free for anyone to deploy anywhere
- Microsoft will support Java 11 until at least 2024, with quarterly updates
- No direct JRE download but JDK Download [link](https://docs.microsoft.com/de-de/java/openjdk/download)

**Comment by TBrandhorst** [comment]
## Red Hat’s OpenJdk Build
- bug fixes for RHEL/CentOS
- Includes JavaFX and Java Web Start
- free and open source implementation of the Java Platform, Standard Edition (Java SE)
- Multiplatform support
- 6 years of support for every major version since ist release. Need to subscripe for the support
